package oj389FindTheDifference;


import java.util.HashMap;
import java.util.Map;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int char_sum_s = 0, char_sum_t = 0;
        for(int i = 0; i < s.length(); i++) {
            char_sum_s += (int)s.charAt(i);
        }
        for(int i = 0; i < t.length(); i++) {
            char_sum_t += (int)t.charAt(i);
        }
        return (char)(char_sum_t - char_sum_s);
    }
}
